## [1] Texts, Labels
## [2] Numericized texts and labels
## [3] Batch :: tuple(text, label)
## [4] text → `EMBEDDING LAYER` → embedded text
## [5] embedded text → `RNN LAYER` → output, hidden state
## [6] hidden state → `LINEAR LAYER` → prediction

In [1]:
import torch
import torch.nn as nn

In [4]:
# dummy examples
texts = torch.tensor([[1 , 2], [2, 3], [3, 0]])  # [sentence length x batch size] → [3, 2]
labels = torch.tensor([0, 1])  # [batch size] → [2]

In [9]:
# hyperparameters
input_dim = 5  # vocabulary size
embedding_dim = 3
hidden_dim = 4
output_dim = 3  # number of classes

In [10]:
# embedding, rnn, and fc layers

embedding = nn.Embedding(input_dim, embedding_dim)  
# (input) texts :: [sentence length x batch size]
# (output) embedded texts:: [sentence length x batch size x embedding dimension]

rnn = nn.RNN(embedding_dim, hidden_dim)
# (input) embedded texts :: [sentence length x batch size x embedding dimension]
# (output_1) output :: [sentence length x batch size x hidden dimension]
# (output_2) hidden state :: [1 x batch size x hidden dimension]

fc = nn.Linear(hidden_dim, output_dim)
# (input) last hidden state :: [1 x batch size x hidden dimension] → [batch size x hidden dimension]
# (output) prediction :: [batch size x output dimension]

In [11]:
print(f'texts:\n{texts, texts.shape}\n\n\n')

embedded = embedding(texts) 
print(f'embedded text:\n{embedded, embedded.shape}\n\n\n')

out, hid = rnn(embedded)
print(f'output:\n{out, out.shape}\n')
print(f'hidden state:\n{hid, hid.shape}\n\n\n')

pred = fc(hid.squeeze())
print(f'prediction:\n{pred, pred.shape}\n')

texts:
(tensor([[1, 2],
        [2, 3],
        [3, 0]]), torch.Size([3, 2]))



embedded text:
(tensor([[[-0.3114,  0.8579,  1.6065],
         [-0.0717,  1.6152, -0.5619]],

        [[-0.0717,  1.6152, -0.5619],
         [ 0.8590, -0.4618,  0.6958]],

        [[ 0.8590, -0.4618,  0.6958],
         [ 2.5485,  1.4779,  0.5817]]], grad_fn=<EmbeddingBackward0>), torch.Size([3, 2, 3]))



output:
(tensor([[[ 0.3752,  0.5606,  0.2854, -0.2116],
         [-0.6983, -0.4774,  0.8035, -0.1856]],

        [[-0.7224, -0.2625,  0.8491,  0.2487],
         [-0.0033,  0.7973,  0.5871, -0.7194]],

        [[-0.1242,  0.8778,  0.5444, -0.7499],
         [-0.8693,  0.7159,  0.9761, -0.6613]]], grad_fn=<StackBackward0>), torch.Size([3, 2, 4]))

hidden state:
(tensor([[[-0.1242,  0.8778,  0.5444, -0.7499],
         [-0.8693,  0.7159,  0.9761, -0.6613]]], grad_fn=<StackBackward0>), torch.Size([1, 2, 4]))



prediction:
(tensor([[-0.1449,  0.5620, -0.3436],
        [-0.3834,  0.4529, -0.0750]], grad_fn=<Add